# Interactive Visualisation

### Objective:
We aim to visualize the distribution of grants issued to different Swiss Cantons by Swiss National Science Foundation.  To achieve this, grant's data is collected from the P3 Grant Export, universities or organizations are geolocalized whith a geographic search API (first suggested Geonames' and later Google's), mapped the location to canton with
the help of a TopoJSON file and folium, and finally the aggregates are presented as a choropleth map.

In [1]:
# A number of libraries are need
import numpy as np
import pandas as pd
import folium
import json
from urllib.request import urlopen
from urllib import parse
import requests

#### Cleaning data
First we load and clean the file, keeping only the information about the monetary amount of funding as well as the university they belong to. The canton it is not directly provided with the dataset, so further work will be put later into mapping universities (or organizations) to cantons.

The database description mentions that the University Field is left **empty** if the project is not carried out in Swiss University. Hence we decide to drop these entries as the money is not used by the Swiss University. There were **12981** such enteries. Furthermore, 'Nicht zuteilbar - NA' is "not assignable" (we don't really know german), so it is excluded too. We perfom a little trick with NPO data, for which we will find the canton association much later given that it needs further search into other parameters.

Funding is often missing too: In these cases our approach is to set the amount to 0 so it will be aggregated into cantons without an impact in our data. This behaviour is easily modifiable in the code below. There are **10990** such projects.

In [49]:
# Loading from csv file on root directory
df = pd.read_csv('P3_GrantExport.csv',sep=';')
data = df.copy()

# Dropping innecessary information
df = df[['University','Approved Amount']]

# Transformation from string to floats in 'Approved Amount' while also dealing with non-numeric values.
float_amounts = list()
for x in df['Approved Amount'].tolist():
    try:
        float_amounts.append(float(x))
    except:
        float_amounts.append(0) #When we are missing a real number we set the amount to 0 (basically to discard it later)
    
df = df[['University']] #we keep only university names associated at projects
df['Funding'] = float_amounts #and we attach float value of the Approved Amount, now renamed to 'Funding'

# Final manual drops
df = df.drop(df.index[(df['University'] ==  'Nicht zuteilbar - NA')])
df = df.drop(df.index[(df['University'] ==  'NPO (Biblioth., Museen, Verwalt.) - NPO')])

# Contains data for NPO
npo_data = data[data['University'] == 'NPO (Biblioth., Museen, Verwalt.) - NPO']

df.head()

                    University  Funding
1    Université de Genève - GE  41022.0
3       Universität Basel - BS  52627.0
5  Université de Fribourg - FR  53009.0
6  Université de Fribourg - FR  25403.0
7      Universität Zürich - ZH  47100.0

Before continuing with the map to cantons, to drastically reduce the number of requests, we can group by university simply accumalating the funding of every project conceded to them.

In [50]:
funding_by_uni = df.groupby('University')[['Funding']].sum()
funding_by_uni.describe()

            Funding
count  7.500000e+01
mean   1.666842e+08
std    4.449057e+08
min    8.000000e+03
25%    1.325184e+06
50%    5.067172e+06
75%    4.010541e+07
max    1.838237e+09

75 different universities (or organizations) with a huge disparity in funding.
Maximum is 3 orders of magnitude bigger than the 1st quantile's top.

#### Expanding data
Now that we have reduced our data to the minimum useful amount, it's time to add some new fields that enhance our capabilities.

We expand our columns to include the Canton and, as an extra, also the longitude and latitude to visualize our universities geolocated in the map.
In an older version, we also notice that the university field can be splited into name of the university and code. This approach helped us to achieve a higher percentage of correct geo-searchs later on, but incurred in some unwanted matches like University of Laussane being associated to ZH! Our final approach simply removes "-" and "(" when forming the query.

In [51]:
# Extra fields
funding_by_uni['Longitude'] = ''; funding_by_uni['Latitude'] = ''; funding_by_uni['Canton'] = ''

#imporving for before search
fbu = funding_by_uni.reset_index()

# Old version expansion
'''
University_name = list()
University_code = list()
for x in fbu.University.tolist():
    try:
        name, code = x.split(' - ') #split by line
    except:
        name, code = x.split(' ') #or split by space (there are some cases in which the split is different)
        
    University_name.append(name)
    University_code.append(code)
fbu['University_name'] = University_name
fbu['University_code'] = University_code

'''

fbu.head()

,University,Funding,Longitude,Latitude,Canton
0,AO Research Institute - AORI,3435621.0,,,
1,Allergie- und Asthmaforschung - SIAF,19169965.0,,,
2,Berner Fachhochschule - BFH,31028695.0,,,
3,Biotechnologie Institut Thurgau - BITG,2492535.0,,,
4,Centre de rech. sur l'environnement alpin - CR...,1567678.0,,,

Now we use Geonames Full Text Search API to map the universities to their respective cantons. 'requests' library is used to get the HTTP response. But since 'University' names have spaces and other special characters, it needs to be UTF-8 encoded before using the requests.get. This is accomplished using 'parse.quote' method in 'urllib' library.

In [ ]:
num_projects = len(fbu)
username = 'dunaiada'

for i in range(0,num_projects):
    
    # Cleaning unnecessary characters for query
    uni_tmp = fbu['University'][i]
    if uni_tmp.find('-') != -1:
        uni_tmp = uni_tmp.replace(uni_tmp[uni_tmp.find('-'):],'')
    if uni_tmp.find('(') != -1:
        uni_tmp = uni_tmp.replace(uni_tmp[uni_tmp.find('('):],'')
        
    # Restricting to country=CH is of critical importance, particularly when usid the code
    url = 'http://api.geonames.org/search?q=' + uni_tmp + '&country=CH' + '&maxRows=1&username=' + username + '&type=json'
    
    ## Encode special characters and spaces
    query = parse.quote(url,safe=':/&=?')
    
    ## Parse JSON data
    d = json.loads(requests.get(query).text)
    
    if bool(d['geonames']): #checks whether we get a match.
        #And because you don't always get all the info, a try-except is needed
        try:
            fbu['Canton'].iloc[i]     = d['geonames'][0]['adminCode1']
            fbu['Latitude'].iloc[i]   = d['geonames'][0]['lat']
            fbu['Longitude'].iloc[i]  = d['geonames'][0]['lng']
        except:
            pass

In [53]:
fbu.head(10)

,University,Funding,Longitude,Latitude,Canton
0,AO Research Institute - AORI,3.435621e+06,,,
1,Allergie- und Asthmaforschung - SIAF,1.916996e+07,,,
2,Berner Fachhochschule - BFH,3.102870e+07,,,
3,Biotechnologie Institut Thurgau - BITG,2.492535e+06,,,
4,Centre de rech. sur l'environnement alpin - CR...,1.567678e+06,,,
5,EPF Lausanne - EPFL,1.175316e+09,,,
6,ETH Zürich - ETHZ,1.635597e+09,8.54805,47.3763,ZH
7,Eidg. Anstalt für Wasserversorgung - EAWAG,7.461922e+07,,,
8,"Eidg. Forschungsanstalt für Wald,Schnee,Land -...",4.836039e+07,,,
9,Eidg. Hochschulinstitut für Berufsbildung - EHB,2.086572e+06,,,

We can see that despite our efforts, still a great number of universities hadn't been associated to their respective cantons. (Not even our lovely EPFL). To attempt to solve this we refer to a different library, geocoder, that allow us to tap into the more powerful google geocoding API.

In [ ]:
import geocoder

num_projects = len(fbu)
for i in range(0,num_projects):
    
    # Cleaning unnecessary characters for query
    uni_tmp = fbu['University'][i]
    if uni_tmp.find('-') != -1:
        uni_tmp = uni_tmp.replace(uni_tmp[uni_tmp.find('-'):],'')
    if uni_tmp.find('(') != -1:
        uni_tmp = uni_tmp.replace(uni_tmp[uni_tmp.find('('):],'')
        
    
    # Here we use google geocoding access
    response = geocoder.google(uni_tmp,components="country:CH")
    json_out = response.json
    
    # If the canton is found, it will appear as 'state' in the JSON
    if 'state' in json_out.keys():
        fbu['Canton'].loc[i]    = json_out['state']
        fbu['Latitude'].loc[i]  = json_out['lat']
        fbu['Longitude'].loc[i] = json_out['lng']

In [55]:
fbu.head(10)

,University,Funding,Longitude,Latitude,Canton
0,AO Research Institute - AORI,3.435621e+06,,,
1,Allergie- und Asthmaforschung - SIAF,1.916996e+07,,,
2,Berner Fachhochschule - BFH,3.102870e+07,,,
3,Biotechnologie Institut Thurgau - BITG,2.492535e+06,9.05574,47.6038,TG
4,Centre de rech. sur l'environnement alpin - CR...,1.567678e+06,,,
5,EPF Lausanne - EPFL,1.175316e+09,6.5676,46.519,VD
6,ETH Zürich - ETHZ,1.635597e+09,8.54809,47.3765,ZH
7,Eidg. Anstalt für Wasserversorgung - EAWAG,7.461922e+07,,,
8,"Eidg. Forschungsanstalt für Wald,Schnee,Land -...",4.836039e+07,,,
9,Eidg. Hochschulinstitut für Berufsbildung - EHB,2.086572e+06,,,

As an intermediate check point, we plot a map with the markers for each geolocated university.
**Please, find it in it's respective html file!**

In [56]:
#Folium commands to generate the map. Note that we only attempt to plot those for which we have coordinates.

map_with_uni_markers = folium.Map(location=[46.76, 8.26], tiles='Mapbox Bright',zoom_start=8)
for indx in range(fbu.shape[0]):
    if fbu.iloc[indx]['Latitude'] != ''  :
        folium.Marker(location=[fbu.iloc[indx]['Latitude'],fbu.iloc[indx]['Longitude']],
                      popup=fbu.iloc[indx]['University']).add_to(map_with_uni_markers)
        
map_with_uni_markers.save('map_with_uni_markers.html') #And finally save to later see in a browser.

There is some improvement. At least we (EPFL) are there now. And if we actually consider how much money had been correctly allocated, missing universities are just small amounts compared to EPFL and ETHZ.

Still, because we want to have an exhaustive represantition, we have taken the time to manually collect the missing cantons. For this, a CSV file had been created with the new inputs. We will work with such file from the last steps of the exercise.

In [57]:
manually_mapped_data = pd.read_csv('missing_mappings.csv',sep=',',encoding = 'cp1252')

In [58]:
val =  fbu.University.isin(manually_mapped_data.University)
fbu.loc[val,'Canton'] = manually_mapped_data['Canton']
fbu.head(10)

,University,Funding,Longitude,Latitude,Canton
0,AO Research Institute - AORI,3.435621e+06,,,GR
1,Allergie- und Asthmaforschung - SIAF,1.916996e+07,,,GR
2,Berner Fachhochschule - BFH,3.102870e+07,,,BE
3,Biotechnologie Institut Thurgau - BITG,2.492535e+06,9.05574,47.6038,TG
4,Centre de rech. sur l'environnement alpin - CR...,1.567678e+06,,,ZH
5,EPF Lausanne - EPFL,1.175316e+09,6.5676,46.519,VD
6,ETH Zürich - ETHZ,1.635597e+09,8.54809,47.3765,ZH
7,Eidg. Anstalt für Wasserversorgung - EAWAG,7.461922e+07,,,SG
8,"Eidg. Forschungsanstalt für Wald,Schnee,Land -...",4.836039e+07,,,TI
9,Eidg. Hochschulinstitut für Berufsbildung - EHB,2.086572e+06,,,ZH

Grouping by cantons and including non-represented cantons is almost the last step of processing in our data

In [59]:
fbc = fbu.groupby('Canton')[['Funding']].sum() #fbc == funding by canton
data = fbc.reset_index()

#We define the full list of cantons manually 
list_of_cantons = ["ZH","BE","LU","UR", "SZ", "OW","NW", "GL", "ZG", "FR", "SO", "BS", "BL", "SH", "AR", "AI",
                   "SG", "GR", "AG", "TG", "TI", "VD", "VS", "NE", "GE", "JU"]

frame_of_cantons = pd.DataFrame(list_of_cantons, columns=['Canton']) #Creates a dataframe from the list to allow merging
extended_data = pd.merge(frame_of_cantons, data, how='left', on="Canton")
extended_data.head()

  Canton       Funding
0     ZH  3.473426e+09
1     BE  1.552404e+09
2     LU  5.971181e+07
3     UR           NaN
4     SZ  9.365510e+05

Remeber when we discarded NPO data? Well, to make it super-complete we are bringing it back!

We saved it in a different file for later processing, now we locate the "Institution" they belong with geocoder and add this data to our current results. Note that this section is mostly done to be thorough. For a laxer implementation the following steps could be excluded.

In [60]:
# Formating the copy that we did before
npo_data_ = pd.DataFrame(npo_data.groupby('Institution').apply(lambda x: x['Approved Amount'].astype(float).sum()))
npo_data_.columns = ['Funding']
npo_data_['Canton'] = ''

#geocoder search
for indx in npo_data_.index :
    response = geocoder.google(indx,components="country:CH")
    json_out = response.json
    if 'state' in json_out.keys():
        npo_data_.loc[indx,'Canton'] = json_out['state']

#Preparing for concatenation with same dimensions
npo_cantons = pd.DataFrame(npo_data_.groupby('Canton').apply(lambda x: x['Funding'].sum()))
npo_cantons.columns = ['Funding']
npo_cantons.reset_index(level=0, inplace=True)
npo_cantons.drop(0, inplace=True)

#Finally we concatenate and groub by Canton adding up the funding again.
# An IMPORTANT NOTE is the role of apply-sum instead of using sum() directly, and it's due to first one retreiving 0 when the second retrieves NAN
extended_data = pd.concat([extended_data, npo_cantons])
extended_data = pd.DataFrame(extended_data.groupby('Canton').apply(lambda x: x['Funding'].sum()))
extended_data.columns = ['Funding']

In [61]:
extended_data.head()

             Funding
Canton
AG      1.152813e+08
AI      0.000000e+00
AR      0.000000e+00
BE      1.552404e+09
BL      4.277191e+07

Some extra touchs before plotting the map and we are ready!

In [ ]:
#Sorting for showing the dataframe in order now:
extended_data.sort_values(by='Funding', ascending=False,inplace=True)

#Reset index for convenience
extended_data.reset_index(level=0, inplace=True)

#Rescaling for readability
extended_data['Funding'] /= 1e6

# We experimented with Log scale but resulted to be more confusing in the map than the linear one.
#extended_data['Funding'] = np.log(extended_data['Funding'])

# Final rename of colums
extended_data.columns = ['Canton', 'Funding(in Millions CHF)']

In [63]:
#And here comes what we've got in numbers:
extended_data

   Canton  Funding(in Millions CHF)
0      ZH               3473.426159
1      VD               2398.901588
2      GE               1872.400274
3      BE               1552.404119
4      BS               1386.802823
5      FR                464.968580
6      NE                424.061105
7      TI                183.348770
8      SG                166.623710
9      AG                115.281349
10     LU                 59.711806
11     BL                 42.771914
12     GR                 25.987378
13     VS                  4.928510
14     TG                  4.018981
15     JU                  3.478469
16     ZG                  2.473055
17     SZ                  0.936551
18     SH                  0.176691
19     AI                  0.000000
20     OW                  0.000000
21     GL                  0.000000
22     SO                  0.000000
23     UR                  0.000000
24     AR                  0.000000
25     NW                  0.000000

#### Visualization
Finally, with all the data collected we can finally perform the visualization with the help of folium. We plot the map using the TopoJSON file (with coordinates for each canton) and using the dataframe containing grant money for each canton.

In [ ]:
topo_path = 'ch-cantons.topojson.json'

m = folium.Map(location=[46.76, 8.26], zoom_start=8, tiles='Mapbox Bright')

m.choropleth(geo_path=topo_path, data=extended_data, columns=['Canton', 'Funding(in Millions CHF)'],
             key_on='feature.id', topojson='objects.cantons', fill_color='YlGn', legend_name = 'Funding (CHF)')

In [65]:
m.save('map_funding_by_canton.html') #Check in a browser!